app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [
    'uses' => 'AuthController@getLogin',
    'as' => 'login'
]);

Route::post('/', [
    'uses' => 'AuthController@postLogin',
    'as' => 'login'
]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('inicio', [
        'uses' => 'UsersController@index',
        'as' => 'inicio'
    ]);

    Route::get('logout', [
        'uses' => 'AuthController@getLogout',
        'as' => 'logout'
    ]);

    Route::resource('usuario', 'UsersController');

});

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'usuarios';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['nome', 'login', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\AuthRequest;
use App\Http\Controllers\Controller;
use Auth;

class AuthController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getLogin()
    {
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function postLogin(AuthRequest $request)
    {
        $input = $request->input();

        $user = [
            'login' => $input['login'],
            'password' => $input['password']
        ];

        if (Auth::attempt($user))
        {
            return redirect()->route('inicio');
        }

        return redirect('/');
    }

    public function getLogout()
    {
        Auth::logout();

        return redirect()->route('login');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

abstract class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;
use Hash;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuarios = User::get();

        return view('conteudo.usuarios.index', compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('conteudo.usuarios.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->input();

        $usuario = new User();
        $usuario->nome = $input['nome'];
        $usuario->login = $input['login'];
        $usuario->password = Hash::make($input['password']);
        $usuario->save();

        return redirect()->route('inicio');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($usuario)
    {
        return view('conteudo.usuarios.form', compact('usuario'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $usuario)
    {
        $input = $request->input();

        $usuario->nome = $input['nome'];
        $usuario->login = $input['login'];
        $usuario->password = Hash::make($input['password']);
        $usuario->save();

        return redirect()->route('inicio');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($usuario)
    {
        $usuario->delete();

        return redirect()->route('inicio');
    }
}

resources/views/conteudo/usuarios/form.blade.php
@extends('layout.default')

@section('content')

<h1>Formulário</h1>

@if (isset($usuario))
{!! Form::open(['route'=>['usuario.update',$usuario],'method'=>'put']) !!}
@else
{!! Form::open(['route'=>'usuario.store','method'=>'post']) !!}
@endif

<div class="row-fluid">
    <div class="col-lg-6">
        {!! Form::label('nome', 'Nome') !!}
        {!! Form::text('nome', (isset($usuario) ? $usuario->nome : old('nome')), ['class'=>'form-control']) !!}
    </div>
</div>
<div class="row-fluid">
    <div class="col-lg-6">
        {!! Form::label('login', 'Login') !!}
        {!! Form::text('login', (isset($usuario) ? $usuario->login : old('login')), ['class'=>'form-control']) !!}
    </div>
</div>
<div class="row-fluid">
    <div class="col-lg-6">
        {!! Form::label('password', 'Senha') !!}
        {!! Form::password('password', ['class'=>'form-control']) !!}
    </div>
</div>
<div class="row-fluid">
    <div class="col-lg-6">
        {!! Form::label('password_confirmation', 'Confirme a senha') !!}
        {!! Form::password('password_confirmation', ['class'=>'form-control']) !!}
    </div>
</div>

<div class="row-fluid pull-right">
    <div class="col-lg-12">
        <a href="{!! URL::route('inicio') !!}" class="btn btn-default">Voltar</a>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
</div>

{!! Form::close() !!}

@endsection

resources/views/conteudo/usuarios/index.blade.php
@extends('layout.default')

@section('content')

<h1>Formulário</h1>

<a href="{!! URL::route('usuario.create') !!}" class="btn btn-primary btn-xs">Criar novo</a>

@if ($usuarios)
<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Login</th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($usuarios as $item)
        <tr>
            <td>{{ $item->nome }}</td>
            <td>{{ $item->login }}</td>
            <td><a href="{!! URL::route('usuario.edit', [$item]) !!}">Editar</a></td>
            <td>
                {!! Form::open(['route'=>['usuario.destroy', $item],'method'=>'delete']) !!}
                <button type="submit" class="btn btn-danger btn-xs">Excluir</button>
                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@else
<div class="well">
    Não há itens a serem exibidos.
</div>
@endif

@endsection

resources/views/layout/default.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>FooBar51</title>

        <!-- Bootstrap -->
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        Bem vindo {{ Auth::user()->nome }}. <a href="{!! URL::route('logout') !!}" class="btn btn-default btn-xs">Sair</a>

        @yield('content')

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    </body>
</html>